# Generated by Django 6.0 on 2026-01-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ing_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prd_Name', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Created_at', models.DateTimeField(auto_now=True)),
                ('ID_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('ingredients', models.ManyToManyField(related_name='products', to='product.ingredient')),
            ],
        ),
    ]
